settings:
  title: 'Status Page'
  url: 'https://status.yorgis.net' # used for Slack messages
  logo: https://kwkzcdfqvquavxhvoaqi.supabase.co/storage/v1/object/public/bucketo/db.jpg?t=2022-09-30T12%3A46%3A15.475Z # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: ynet # unique identifier
    name: yorgis.net
    description: 'yorgis.net the best site in the world' # default=empty
    url: 'https://yorgis.net/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: ssrynet
    name: ssr.yorgis.net
    description: 'Funny Thing'
    url: 'https://ssr.yorgis.net'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: timeynet
    name: time.yorgis.net
    url: 'https://time.yorgis.net/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
  
  
  - id: gdynet
    name: geodata.yorgis.net
    url: 'https://geodata.yorgis.net/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
   
   
   - id: mynet
    name: m.yorgis.net
    url: 'https://m.yorgis.net/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
    
  
