settings:
  title: 'Status Page'
  url: 'https://status.yorgis.net' 
  logo: https://kwkzcdfqvquavxhvoaqi.supabase.co/storage/v1/object/public/bucketo/db.jpg?t=2022-09-30T12%3A46%3A15.475Z 
  daysInHistogram: 90 
  collectResponseTimes: true 

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' 

monitors:
  - id: ynet 
    name: yorgis.net
    description: 'yorgis.net the best site in the world' 
    url: 'https://yorgis.net/' 
    method: GET 
    expectStatus: 200 
    followRedirect: false 
    linkable: true

  - id: ssrynet
    name: ssr.yorgis.net
    description: 'Funny Thing'
    url: 'https://ssr.yorgis.net'
    method: GET
    expectStatus: 200
    linkable: true 
    
    
    
  - id: tdappynet
    name: todoapp.yorgis.net
    description: 'The best todo app!!'
    url: 'https://todoapp.yorgis.net'
    method: GET
    expectStatus: 200
    linkable: true 
    
  - id: mynet
   name: m.yorgis.net
   description: 'The mobile version of yorgis.net!!'
   url: 'https://m.yorgis.net'
   method: GET
   expectStatus: 200
   linkable: true 

 
