name = "status"
workers_dev = true
account_id = "747c9af393e7af3bd33dd64d5c84767c"
type = "webpack"
webpack_config = "node_modules/flareact/webpack"
compatibility_date = "2024-05-04"
main = "./index.js"

[triggers]
crons = ["*/1 * * * *"]

[site]
bucket = "out"

# uncomment and adjust following if you are not using GitHub Actions
#[env.production]
#kv-namespaces = [{binding="KV_STATUS_PAGE", id="xxxx", preview_id=""}]
#zone_id="xxx"
#route="xxx"
